### PR TITLE
MNT Add behat tests

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripeltd/product-issues/issues/473

### CODE REVIEW

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
Doesn't look that this one has any CI running on it.

**Comment by emteknetnz** [comment]
@maxime-rainville have added CI

**Comment by emteknetnz** [comment]
^ I ended up backporting the phpunit9 stuff into this PR to 3.0 to make CI happy

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
Looks like behat is failing but it's not failing the build.

image

**Review by maxime-rainville — APPROVED** [review]
LGTM

**Pull request merged**
